In [7]:
import numpy as np
np.array([1,2,3,4,"A","B","I","100"])

array(['1', '2', '3', '4', 'A', 'B', 'I', '100'], dtype='<U11')

In [8]:
np.array([12,24.5,9.8]).astype(int)

array([12, 24,  9])

In [9]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.array([1,2,3,4,5,6],ndmin=3)


array([[[1, 2, 3, 4, 5, 6]]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
e_consump=np.array([1200,3400,2900,1800,2500])
print(e_consump)

[1200 3400 2900 1800 2500]


In [ ]:
t_cons=e_consump.sum()
a_cons=e_consump.mean()
v_cons=e_consump.var()
std_cons=v_cons**0.5
std2_cons=e_consump.std()
print(t_cons,a_cons,v_cons,std_cons,std2_cons)

11800 2360.0 610400.0 781.2809993849844 781.2809993849844


In [ ]:
print(np.shape(e_consump))

(5,)
