In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
dff=pd.read_csv("/content/sample_data/crop_yield_data.xls")
dff

temperature  humidity  rainfall  soil_quality  fertilizer_used  crop_yield
0           25        60        50             7              200        2000
1           28        65        60             6              220        2200
2           24        58        40             8              180        1800
3           26        62        55             7              210        2100
4           22        59        45             6              190        1900
5           30        70        70             7              250        2500
6           23        64        65             6              240        2300
7           27        63        50             8              200        2200
8           29        68        75             7              230        2400
9           25        60        55             6              210        2100

In [29]:
X=dff.drop(["crop_yield"],axis=1)
y=dff[["crop_yield"]]
X.shape,y.shape

((10, 5), (10, 1))

In [30]:
from sklearn.preprocessing import MinMaxScaler #to match the numbers and weights in DL
scaler=MinMaxScaler()
X_s=scaler.fit_transform(X)
y_s=scaler.fit_transform(y.values.reshape(-1,1)) #y.values -> it changes Series(list) to array.
X_s,y_s

(array([[0.375     , 0.16666667, 0.28571429, 0.5       , 0.28571429],
        [0.75      , 0.58333333, 0.57142857, 0.        , 0.57142857],
        [0.25      , 0.        , 0.        , 1.        , 0.        ],
        [0.5       , 0.33333333, 0.42857143, 0.5       , 0.42857143],
        [0.        , 0.08333333, 0.14285714, 0.        , 0.14285714],
        [1.        , 1.        , 0.85714286, 0.5       , 1.        ],
        [0.125     , 0.5       , 0.71428571, 0.        , 0.85714286],
        [0.625     , 0.41666667, 0.28571429, 1.        , 0.28571429],
        [0.875     , 0.83333333, 1.        , 0.5       , 0.71428571],
        [0.375     , 0.16666667, 0.42857143, 0.        , 0.42857143]]),
 array([[0.28571429],
        [0.57142857],
        [0.        ],
        [0.42857143],
        [0.14285714],
        [1.        ],
        [0.71428571],
        [0.57142857],
        [0.85714286],
        [0.42857143]]))

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_s, y_s, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8, 5), (2, 5), (8, 1), (2, 1))

In [32]:
model=Sequential()
model.add(Dense(64,activation="relu",input_dim=X_train.shape[1]))
model.add(Dense(32,activation="relu"))
model.add(Dense(1))
model.compile(optimizer="adam",loss="mse")
model.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.2444
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2154
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.1899
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.1663
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1450
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1257
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.1082
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0927
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0790
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0665
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0556
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0465
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0390
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0331
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0285
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━

In [33]:
data=np.array([[25,60,50,7,200]])
model.predict(data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step


array([[70.51135]], dtype=float32)